"use client"
import Nav from '../components/Nav'
import './globals.css'
import { Kumbh_Sans } from 'next/font/google'


const inter = Kumbh_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
